### PR TITLE
tests: Don't run GPG tests if support is disabled in OSTree

### PR DESCRIPTION
**Pull request by refi64**
It's entirely possible for a system to have gpg installed, but OSTree itself was built with GPG signature support disabled. In that case, skip the GPG tests.

Signed-off-by: Ryan Gonzalez <ryan.gonzalez@collabora.com>

### CODE REVIEW

**Review by dbnicholson — APPROVED** [review]
The other way to do this is that is sadly undocumented is to use the `OSTree.BUILT_FEATURES` string. It's what you see when you do `ostree --version`. Like `'gpgme' in OSTree.BUILT_FEATURES.split()`. But this way works well and is probably more robust as a full feature test.

**Comment by dbnicholson** [comment]
@refi64 Are you planning to push any more features or fixes? If not, I'll cut a release with the new sign features.

**Comment by refi64** [comment]
Given that I spent ages looking exactly for what seems to be `BUILT_FEATURES`, I was about to be slightly irritated with myself...but trying to access it from introspection is giving me an `AttributeError`, so I'll just ignore that for now :sweat_smile:

> Are you planning to push any more features or fixes?

Not that I'm aware of, though we plan to deploy a version with the new updates shortly (i.e. this hasn't been fully tested in our production context yet).

**Comment by dbnicholson** [comment]
> Given that I spent ages looking exactly for what seems to be `BUILT_FEATURES`, I was about to be slightly irritated with myself...but trying to access it from introspection is giving me an `AttributeError`, so I'll just ignore that for now sweat_smile

Ah, yes. I see it was recently [kneecapped](https://github.com/ostreedev/ostree/commit/3e645ad950c3193d50ac9924ec7eba43c5df4cb5). The ostree on my system predates that.

> > Are you planning to push any more features or fixes?
> 
> Not that I'm aware of, though we plan to deploy a version with the new updates shortly (i.e. this hasn't been fully tested in our production context yet).

Alright. I'll probably roll a release today or tomorrow. If you find anything in testing, we can roll another. I'm interested to hear how it goes!

**Pull request merged**
